# Generated by Django 3.2.5 on 2021-07-05 08:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('summary', models.TextField()),
                ('category', models.CharField(choices=[('1', 'Novel_Poem'), ('170', 'Economic_Management'), ('1230', 'Home_Cook_Beauty'), ('1237', 'Religion_Mysticism'), ('517', 'Art_Culture'), ('76001', 'Reference_Book'), ('55890', 'Health_Hobby_Leisure'), ('987', 'Science'), ('74', 'History'), ('336', 'Self_Improvement'), ('1196', 'Travel'), ('55889', 'Essay'), ('656', 'Humanities')], max_length=50)),
                ('author', models.CharField(max_length=100)),
            ],
        ),
    ]
