# Generated by Django 3.2.5 on 2021-07-07 03:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20210706_1506'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bestseller',
            fields=[
                ('title', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('author', models.CharField(max_length=100)),
                ('url', models.TextField()),
                ('image', models.TextField()),
            ],
        ),
    ]
