# Generated by Django 3.2.5 on 2021-07-08 02:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_bestseller'),
    ]

    operations = [
        migrations.AddField(
            model_name='bestseller',
            name='date',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='bestseller',
            name='flag',
            field=models.CharField(default=1, max_length=10),
            preserve_default=False,
        ),
    ]
