# Generated by Django 3.2.5 on 2021-07-08 02:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_auto_20210708_1138'),
    ]

    operations = [
        migrations.AddField(
            model_name='bestseller',
            name='id',
            field=models.BigAutoField(auto_created=True, default=1, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='bestseller',
            name='title',
            field=models.CharField(max_length=100),
        ),
    ]
