# Generated by Django 3.2.5 on 2021-07-08 07:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_alter_bestseller_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='src',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
    ]
